config/routes.rb
Rails.application.routes.draw do

  root :to => 'bouts#index'

  resources :bouts do
    resources :options
    resources :comments
  end

end

app/models/bout.rb
class Bout < ActiveRecord::Base
  has_many :options
  has_many :comments
  accepts_nested_attributes_for :options
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bout
  validates :name, :presence => true
  validates :body, :presence => true
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :bout
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bouts_controller.rb
class BoutsController < ApplicationController

  def index
    @bouts = Bout.all
  end

  def show
    @bout = Bout.find(params[:id])
  end

  def new
    @bout = Bout.new
    1.times {@bout.options.build}
  end

  def create
    @bout = Bout.new(bout_params)
    if @bout.save()
      respond_to do |format|
        format.html {redirect_to bouts_path}
        format.js
      end
    else
      render :new
    end
  end

  private

  def bout_params
    params.require(:bout).permit(:created_at, options_attributes: [:description, :name])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @bout = Bout.find(params[:bout_id])
    @comment = @bout.comments.create(comment_params)
    if @comment.save()
      respond_to do |format|
        format.html {redirect_to bout_path(@bout)}
        format.js
      end
    else
      render :new
    end
  end

  def edit
  end

  def new
    @bout = Bout.find(params[:bout_id])
    @comment = @bout.comments.new
  end

  def update
  end

  def destroy
    @bout = Bout.find(params[:bout_id])
    @comment = @bout.comments.find(params[:id])
    @comment.destroy
    redirect_to bout_path(@bout)
  end

private

  def comment_params
    params.require(:comment).permit(:name, :body)
  end

end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  def index
    @options = Option.all
  end
  #
  # def show
  # end
  #
  # def new
  #   @bout = Bout.find(params[:bout_id])
  #   @option = @bout.options.new
  # end

  def update
      @bout = Bout.find(params[:bout_id])
      @option = @bout.options.find(params[:id])
      if @option.update(votes: @option.votes + 1)
        respond_to do |format|
          format.html { redirect_to bouts_path }
          format.js
        end
      end
    end


  private

  def option_params
    params.require(:option).permit(:name, :description, :votes)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bouts_helper.rb
module BoutsHelper
end

app/views/bouts/_bout.html.erb
<li><%= link_to "Bout bout.id ", bout_path(bout) %></li>
  <ul>
    <% bout.options.order(created_at: :desc).each do |option| %>
    <li class="option"><span class="vote_button"><%= link_to "vote", bout_option_path(bout, option), remote: true, method: :patch %></span> <%= option.description %> - <span id="<%= option.id %>"><%= option.votes %></span></li>
    <% end %>
  </ul>
  </ul>

app/views/bouts/_form.html.erb
<%= form_for @bout, id: "new_bout", remote: true, authenticity_token: true do |f| %>
  <%= f.fields_for :options do |option_fields| %>
    <%= option_fields.label :name %>
    <%= option_fields.text_field :name %>
    <%= option_fields.label :description, "Option A" %>
    <%= option_fields.text_field :description %>
  <% end %>
<br />
  <%= f.fields_for :options do |option_fields| %>
  <%= option_fields.label :name %>
  <%= option_fields.text_field :name %>
    <%= option_fields.label :description, "Option B" %>
    <%= option_fields.text_field :description %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/bouts/create.js.erb
$('#new_bout').remove();
$('#new_bout_link').show();
$('#bouts').append('<%= j render(@bout) %>');

app/views/bouts/index.html.erb
<h1>All bouts</h1>
<ul id="bouts">
  <% @bouts.each do |bout| %>
    <li><%= link_to bout.options.name, bout_path(bout) %></li>
      <ul>
        <% bout.options.order(created_at: :desc).each do |option| %>
        <li class="option"><span id="<%= option.bout_id %>"><%= link_to "vote", bout_option_path(bout, option), remote: true, method: :patch %></span> <%= option.description %> - <span id="<%= option.id %>" class="votes_<%=option.bout_id %>"><%= option.votes %></span></li>
        <% end %>
      </ul>
  <% end %>
</ul>

<%= link_to "New Bout", new_bout_path, id: "new_bout_link", class:"btn btn-default", remote: true %>

app/views/bouts/new.js.erb
$('#new_bout_link').hide().after('<%= j render("form") %>')

app/views/bouts/show.html.erb
<%= link_to "New Comment", new_bout_comment_path(@bout), id: "new_comment_link", class:"btn btn-default", remote: true %>
<hr>
<div id="comments">
  <h4>This bout has <%= @bout.comments.count %> comments:</h4><br>
  <% @bout.comments.each do |comment| %>
    <hr>
    <strong>Name:</strong> <%= comment.name %><br><br>
    <strong>Body:</strong> <%= comment.body %>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<hr><div class="comment">
  <div class="comment_content">
    <h5>Name: <%= comment.name %> </h5>
    <h4><%= comment.body %></h4>
    <em><p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p></em>
  </div>
    <p><%= link_to 'Delete Comment', [comment.bout, comment],
    method: :delete,
    class: "button",
      data: { confirm: 'Are you sure you want to delete this comment?' } %></p>
  </div>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@bout, @bout.comments.build]) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
  <br>
<% end %>
<hr>

app/views/comments/create.js.erb
$('#new_comment').remove();
$('#new_comment_link').show();
$('#comments').append('<%= j render(@comment) %>');

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/new.js.erb
$('#new_comment_link').hide().after('<%= j render("form") %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WouldYouRather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/options/_form.html.erb
<%= form_for @bout do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <p><%= f.submit %></p>

app/views/options/new.js.erb
// $('#new_bout').hide().after('<%= j render("form") %>')

app/views/options/update.js.erb
$('#vote_button').remove();
$('span#<%= @option.id %>').show();
$(".option span#<%= @option.id %>").text("<%= @option.votes %>");